import sys
sys.path.append('./nwk')
sys.path.append('./wk')
sys.path.append('./src')
import PrivKVD
import PrivKV
import PrivKVM
import PrivKVMplus
import Map
import gen
import numpy as np

# All needed parameters
u = 1000
k = 4
e1 = 0.2
e2 = 0.2
c = 4
A0 = 0.1
# S1 is discretized value
S1 = gen.generator(u,k).gen_new()
# nfstar is the result of PrivKVD
# time1_start
nfstar = PrivKVD.PrivKVD(S1,k,e1) 
# time1_end
K=[]
for index in range(k):
    K.append('tmp')
# S2 is for PrivKV and generated by S1
# time2_start !!! must include map procedure
S2 = np.array([Map.map(si,k) for si in S1])
vec = PrivKV.PrivKV(S2,K,e1,e2)
fstar = vec[0]
# time2_end
# time3_start
S3 = np.array([Map.map(si,k) for si in S1])
vec = PrivKVM.PrivKVM(S3,K,e1,c)
mfstar = vec[0]
# time3_end
# time4_start
S4 = np.array([Map.map(si,k) for si in S1])
vec = PrivKVMplus.PrivKVMplus(S4,K,e1,A0)
pfstar = vec[0]
# time4_end
